# Generated by Django 5.2.7 on 2025-10-25 03:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('card_type', models.CharField(choices=[('virtual', 'Virtual Card'), ('physical', 'Physical Card')], max_length=20)),
                ('card_number', models.CharField(max_length=19)),
                ('expiry_date', models.DateField()),
                ('cvv', models.CharField(max_length=3)),
                ('purchase_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purchase_status', models.CharField(choices=[('pending_payment', 'Pending Payment'), ('paid', 'Paid'), ('issued', 'Issued'), ('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending_payment', max_length=20)),
                ('payment_deadline', models.DateTimeField()),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CardPurchase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('merchant', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.card')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
